### ISSUE TITLE
Logging to stdout in Cloud Run creates a JSON object as "message"

### ISSUE THREAD

**Issue by SoftMemes** [googleapis/nodejs-logging-winston#704]
#### Environment details

  - OS: Ubuntu 20 LTS
  - Node.js version: v16.14.2
  - npm version: yarn 3.2.0
  - `@google-cloud/logging-winston` version: 4.2.3

#### Steps to reproduce

When enabling structured logging to STDOUT, I do recieve a structured JSON payload as output, that is picked up by Stackdriver from the Cloud Run logs, so far so good. The "message" however, is in itself a JSON payload containing a "message" key with the original logged message, as well as a "metadata" key of an empty object. As a result, each line in my log output in Stackdriver shows a JSON object (that can then be expanded to show the outer JSON object).

I have attempted to change the format that Windsor is using, but it does not appear to be a problem at that level, without this transport, I am seeing plain text "message" output.

Is there a way to prevent this extra level of object being created and instead have the "message" be just the string I've logged?

**Comment by losalex** [comment]
@SoftMemes, thank you for opening the issue!
Just to be clear on repro steps, would you please be kind to share the exact code and output you see? This would help with a repro and also would clarify better expected results.

**Comment by leoschweizer** [comment]
Facing the same issue (I guess) when logging from Cloud Functions:

<img width="759" alt="Screenshot 2022-06-07 at 17 11 03" src="https://user-images.githubusercontent.com/428354/172423925-c6e808f6-c590-48b6-9a81-8fe84b0f7d61.png">

also notice the wrong logName field.

Minimal code which produces this:
```js
const functions = require('@google-cloud/functions-framework');
const { LoggingWinston } = require('@google-cloud/logging-winston');
const winston = require('winston');

const loggingWinston = new LoggingWinston({
    redirectToStdout: true,
})

const logger = winston.createLogger({
    level: 'debug',
    transports: [
      loggingWinston,
    ],
});

functions.http('helloLog', (req, res) => {
    logger.info('test 123', { some_meta: 123 })
    res.send('Hello');
});

```

package.json:
```json
{
  "name": "logtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.1.2",
    "@google-cloud/logging-winston": "^5.1.0",
    "winston": "^3.7.2"
  }
}
```

**Comment by losalex** [comment]
Thank you @leoschweizer for reproduction steps and output - really appreciate your efforts!
It seems that the `message` containing logged text "test 123" should be added directly under `jsonPayload` (without extra `message` wrapper as show in Logging Explorer screenshot) - please let me know if that would be desired outcome.
I am reaching out to our Cloud Run and Cloud Functions team since the standard output logging has some protocol to follow when logs are collected from stdout in those environments.

**Comment by leoschweizer** [comment]
@losalex yes exactly - the "wrapping" `message` just shouldn't be there, the contained `message` and `metadata` should be added to the log object one level higher

**Comment by steren** [comment]
Cloud Run PM here.

Can the module maintainers comment on what is the serialized JSON that is sent to `stdout` when developers call `logger.info('test 123', { some_meta: 123 })`?

As far as I know, Cloud Run will parsed any serialized JSON and use it "as is" in `jsonPayload`. 

To report a bug on Cloud Run, please manually write serialized JSON to `stdout`. If this works as expected (and last time I checked it did), then the `nodejs-logging-winston` module itself is responsible for the issue.

**Comment by Allezxandre** [comment]
If that can be of any help, I've attempted a fix on a fork, and it turns out the issue is the nodejs-logging package, see here for my fix attempt: https://github.com/prgm-dev/nodejs-logging/commit/a220caea5a4f6e77038b91801889dc308175b539

**Comment by losalex** [comment]
Thanks @Allezxandre and @steren for your input!

@steren , I was trying to run 2 test cases and below the result:

1.      I added following code to CF and run it:

```js
const record = '{"jsonPayload": {"some_meta": 123}}';
console.log(record);
```

The output was:

```json
{
  "insertId": "62ad1e540004e1150e264277",
  "jsonPayload": {
    "jsonPayload": {
      "some_meta": 123
    }
  },
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "project_id": "project",
      "function_name": "logging-function"
    }
  },
  "receiveTimestamp": "2022-06-18T00:37:40.326341043Z"
}
```

2.    Another try was with following code:

```js
const record = '{"jsonPayload": {"some_meta": 123}}';
console.log(record);
```
The output was:

**Comment by steren** [comment]
Sorry, there might be a misunderstanding about the behavior of the Cloud Run platform: You do not need to pass `jsonPayload`. Instead, if valid JSON is logged, then Cloud Run will parse it and add it to `jsonPayload` of the LogEntry

Let me give examples:

### Valid JSON

```
const record = '{"some_meta": 123}';
console.log(record);
```

Will result in 

```
{
  "insertId": "..."
  "jsonPayload": {
      "some_meta": 123
  },
  "resource": {
   ...
  },
}
```

### Invalid JSON

```
const record = '{invalid_json: 123}';
console.log(record);
```

Will result in 

```
{
  "insertId": "..."
  "textPayload": "{invalid_json: 123}",
  "resource": {
   ...
  },
}
```

**Comment by losalex** [comment]
Thanks @steren for clarifications! I will take a deeper look into existing code and the change proposed by @Allezxandre to see what can be done. At this point seems that any change might be a breaking one (e.g. some people currently using logs with extra "message" field and might need existing queries to be adjusted), so I will try to come up with proper fix.

**Comment by Allezxandre** [comment]
While the change will most likely be breaking (like the one I proposed where I simply hoist the attributes by one level), it only happens in one branch of the code with `redirectToStdout: true` (the LogSync part). And I would argue this setting was likely not used by many (even outside of Winston) due to its being broken with the double wrapping of `"message"`.

If that can be of any help, I can open a PR to `nodejs-logging` with my changes (I haven't done so yet as this was intended as a quick fix and I would need to review the contributing guidelines of first)

**Comment by Algirdyz** [comment]
Furthermore, due to this structured message format, serviceContext does not get added correctly to ErrorReporting page.

![image](https://user-images.githubusercontent.com/7482324/176874186-cc14fc93-de9a-495e-8d58-7e5ce4d54ee4.png)

Here is an example of two errors coming from two applications. The one that says preception-api has `redirectToStdout` set to false and reads the serviceContext correctly. The one that says gke_instances has `redirectToStdout` set to true and has a nested service_context.

**Comment by losalex** [comment]
I believe this is fixed for now by [724](https://github.com/googleapis/nodejs-logging-winston/pull/724) - please let me know if you have any issues

**Comment by mbrevda** [comment]
I'm confused - I'm on `v5.1.2` of this package, yet still see logs like:
<img width="1080" alt="Screen Shot 2022-07-29 at 11 37 20 AM" src="https://user-images.githubusercontent.com/293004/181719769-78200880-4ad9-4e4b-903b-0e461f96033f.png">

where I'd expect to see just the message. `redirectToStdout` is set to true - do I need to do anything else?

**Comment by allezxandre** [comment]
> `redirectToStdout` is set to true - do I need to do anything else?

Yes, you need to set `useMessageField` to `false` (defaults to `true`). This option is here to avoid breaking code of users relying on the bug in the current minor version.

See the updated docs here: https://github.com/googleapis/nodejs-logging-winston#alternative-way-to-ingest-logs-in-google-cloud-managed-environments

**Comment by losalex** [comment]
Indeed - it is documented [here](https://github.com/googleapis/nodejs-logging-winston#alternative-way-to-ingest-logs-in-google-cloud-managed-environments).

**Comment by Wazbat** [comment]
> Yes, you need to set `useMessageField` to `false` (defaults to `true`). This option is here to avoid breaking code of users relying on the bug in the current minor version.

Ah this makes sense. I was a little confused as to what the exact purpose of that property was. I feel the example in the docs could be a little more fleshed out as it's currently a bit confusing

**Comment by space-admiral** [comment]
After searching quite a bit, I found the `useMessageField` to be the solution after reading this thread, having thoroughly looked through the documentation.

Would it be possible to update your documentation to link to this issue or explain that when setting redirectToStdout to true, you very likely want to be changing the default useMessageField to false, and that the value for `true` appears to only be a default because people might be depending on the previous, broken implementation that logged nested objects of data.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/80379295/222338613-83777f9f-be16-4f1c-928b-34b2bcf989d6.png">

Much appreciated!

**Comment by macrozone** [comment]
i also got into this pitfall, the documentation should definitly be updated.
